# Generated by Django 4.0.2 on 2022-02-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Collection')),
                ('amount', models.IntegerField(verbose_name='Total number of coins in collection')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_number', models.IntegerField(verbose_name='# Coin')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('agno', models.IntegerField(verbose_name='Year of creation')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('id_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
    ]
