# Generated by Django 4.0.2 on 2022-02-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='agno',
            new_name='year',
        ),
    ]
