# Generated by Django 4.0.2 on 2022-02-11 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='user',
        ),
        migrations.AddField(
            model_name='collector',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Passaword'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='UserName'),
            preserve_default=False,
        ),
    ]
