# Generated by Django 4.0.2 on 2022-02-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_collector_user_collector_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='coins',
            field=models.ManyToManyField(blank=True, null=True, to='api.Coin'),
        ),
    ]
